### PR TITLE
Fixes for Zeek v5.0.0+

### PR DESCRIPTION
**Pull request by mmguero**
This PR addresses issue #15 

The issues fixed are some differences (deprecations removed, I believe) in syntax of some redefined sets/tables, and fixing some warnings about local variables `used inside "when" statement but not captured`

These changes should be backwards compatible as well (although I did have to use an `@if ( Version::number >= 50000 )` directive for the `when` changes for them to be backwards compatible).

### CODE REVIEW

**Comment by mavam** [comment]
Looking forward to see this getting merged!

**Comment by m1357** [comment]
Is this fix getting merged anytime soon?

**Comment by mmguero** [comment]
These fixes should work for Zeek v5.2.0 as well as far as I know. Anyone monitoring this?

**Comment by mmguero** [comment]
ping? anybody home?

**Comment by 00willo** [comment]
I see that the two MITRE contributors (@mfrndz and @johnwunder) haven't had any public activity on GitHub over the past year.  I might see if I can ping someone on the Corelight side who may be able to contact someone in MITRE to give this a bit of love.

**Comment by mmguero** [comment]
That would be awesome. I know that some people are starting to use my branch but of course it would be better in general for the upstream to be usable.

**Comment by johnwunder** [comment]
Hi everyone! Apologies for missing this -- someone just pointed us to it and we're reviewing now to be able to merge.

Thanks so much for the PR!

**Review by mfrndz — APPROVED** [review]

**Comment by mfrndz** [comment]
Thank you for submitting the pull request, and thank you for your patience.

**Pull request merged**
